// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251029084019_Module Table")]
    partial class ModuleTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("BackendApi.Entities.ModuleDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Modules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "socle",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            Label = "in",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 3,
                            Label = "out",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 4,
                            Label = "orchestrateur",
                            ProductId = 1
                        });
                });

            modelBuilder.Entity("BackendApi.Entities.ProductDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessUnitId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusinessUnitId = 1,
                            Label = "ElloHono"
                        },
                        new
                        {
                            Id = 2,
                            BusinessUnitId = 1,
                            Label = "ElloAdjuster"
                        },
                        new
                        {
                            Id = 3,
                            BusinessUnitId = 1,
                            Label = "Sinaps"
                        },
                        new
                        {
                            Id = 4,
                            BusinessUnitId = 1,
                            Label = "Push REC"
                        },
                        new
                        {
                            Id = 5,
                            BusinessUnitId = 2,
                            Label = "ElloAuto"
                        },
                        new
                        {
                            Id = 6,
                            BusinessUnitId = 3,
                            Label = "ElloWorld"
                        });
                });

            modelBuilder.Entity("BackendApi.Entities.TeamDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "Girafe"
                        },
                        new
                        {
                            Id = 2,
                            Label = "Toucan"
                        },
                        new
                        {
                            Id = 3,
                            Label = "Phénix"
                        },
                        new
                        {
                            Id = 4,
                            Label = "Jaguar"
                        },
                        new
                        {
                            Id = 5,
                            Label = "Tiger"
                        },
                        new
                        {
                            Id = 6,
                            Label = "Panther"
                        },
                        new
                        {
                            Id = 7,
                            Label = "Hibou"
                        },
                        new
                        {
                            Id = 8,
                            Label = "Linx"
                        },
                        new
                        {
                            Id = 9,
                            Label = "Caméléon"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
