// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("BackendApi.Models.TeamDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "Girafe"
                        },
                        new
                        {
                            Id = 2,
                            Label = "Toucan"
                        },
                        new
                        {
                            Id = 3,
                            Label = "Phénix"
                        },
                        new
                        {
                            Id = 4,
                            Label = "Jaguar"
                        },
                        new
                        {
                            Id = 5,
                            Label = "Tiger"
                        },
                        new
                        {
                            Id = 6,
                            Label = "Panther"
                        },
                        new
                        {
                            Id = 7,
                            Label = "Hibou"
                        },
                        new
                        {
                            Id = 8,
                            Label = "Linx"
                        },
                        new
                        {
                            Id = 9,
                            Label = "Caméléon"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
